# Generated by Django 3.0.2 on 2020-01-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='data_de_compra',
            field=models.DateField(auto_now_add=True, default='2020-01-07', verbose_name='Data de Compra'),
            preserve_default=False,
        ),
    ]
