# Generated by Django 3.0.2 on 2020-01-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_produto_data_de_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='data_de_compra',
            field=models.DateField(verbose_name='Data de Compra'),
        ),
    ]
